#!/bin/sh
#SBATCH --account=def-ubcxzh
#SBATCH --cpus-per-task=8
#SBATCH --mem=40g
#SBATCH --time=16:00:00
module load StdEnv/2023 r/4.3.1
Rscript ./scnario2/code/problem.R $1 $2 > ./scnario2/rout/problem.Rout 2>&1